import { CSSProperties, ReactElement, ReactNode, useEffect, useState } from "react"
import { SoildBrush } from "./Brush"
import { Colors } from "./Color"
import PropTypes from 'prop-types'
import React from "react"
import { BorderProps } from "./Border"
// type WindowProps={
//     title?:string,
//     children:ReactNode|string
// }

// type GreetProps = { age: number } & typeof defaultProps;

// const defaultProps = {
//   age:21
// };

// type WindowProps={
//     background?:SoildBrush
//     children:ReactNode|string
// }& typeof defaultProps;
// const defaultProps={
//     background:new SoildBrush(Colors.Red)
// }

type WindowProps = {
    background?: SoildBrush
    children: ReactElement
}

//https://jaketrent.com/post/change-parent-on-child-focus-react/
//https://www.google.com/search?q=React.cloneElement&rlz=1C1ONGR_zh-TWTW1004TW1004&sourceid=chrome&ie=UTF-8
const Window = (props: WindowProps) => {

    const [style, setStyle] = useState<CSSProperties>();
    useEffect(() => {
        setStyle({
            display: 'grid',
            width: '100vw',
            height: '100vh',
            //gridColumnStart
            backgroundColor: `${props.background?.ToCSS()}`
        })
    }, [props])
    const rr = ()=>{

    }
    const styleObj: CSSStyleDeclaration = {
        width: '100px',
        height: '100px',
        backgroundColor: 'red',
        accentColor: "",
        alignContent: "",
        alignItems: "",
        alignSelf: "",
        alignmentBaseline: "",
        all: "",
        animation: "",
        animationComposition: "",
        animationDelay: "",
        animationDirection: "",
        animationDuration: "",
        animationFillMode: "",
        animationIterationCount: "",
        animationName: "",
        animationPlayState: "",
        animationTimingFunction: "",
        appearance: "",
        aspectRatio: "",
        backdropFilter: "",
        backfaceVisibility: "",
        background: "",
        backgroundAttachment: "",
        backgroundBlendMode: "",
        backgroundClip: "",
        backgroundImage: "",
        backgroundOrigin: "",
        backgroundPosition: "",
        backgroundPositionX: "",
        backgroundPositionY: "",
        backgroundRepeat: "",
        backgroundSize: "",
        baselineShift: "",
        blockSize: "",
        border: "",
        borderBlock: "",
        borderBlockColor: "",
        borderBlockEnd: "",
        borderBlockEndColor: "",
        borderBlockEndStyle: "",
        borderBlockEndWidth: "",
        borderBlockStart: "",
        borderBlockStartColor: "",
        borderBlockStartStyle: "",
        borderBlockStartWidth: "",
        borderBlockStyle: "",
        borderBlockWidth: "",
        borderBottom: "",
        borderBottomColor: "",
        borderBottomLeftRadius: "",
        borderBottomRightRadius: "",
        borderBottomStyle: "",
        borderBottomWidth: "",
        borderCollapse: "",
        borderColor: "",
        borderEndEndRadius: "",
        borderEndStartRadius: "",
        borderImage: "",
        borderImageOutset: "",
        borderImageRepeat: "",
        borderImageSlice: "",
        borderImageSource: "",
        borderImageWidth: "",
        borderInline: "",
        borderInlineColor: "",
        borderInlineEnd: "",
        borderInlineEndColor: "",
        borderInlineEndStyle: "",
        borderInlineEndWidth: "",
        borderInlineStart: "",
        borderInlineStartColor: "",
        borderInlineStartStyle: "",
        borderInlineStartWidth: "",
        borderInlineStyle: "",
        borderInlineWidth: "",
        borderLeft: "",
        borderLeftColor: "",
        borderLeftStyle: "",
        borderLeftWidth: "",
        borderRadius: "",
        borderRight: "",
        borderRightColor: "",
        borderRightStyle: "",
        borderRightWidth: "",
        borderSpacing: "",
        borderStartEndRadius: "",
        borderStartStartRadius: "",
        borderStyle: "",
        borderTop: "",
        borderTopColor: "",
        borderTopLeftRadius: "",
        borderTopRightRadius: "",
        borderTopStyle: "",
        borderTopWidth: "",
        borderWidth: "",
        bottom: "",
        boxShadow: "",
        boxSizing: "",
        breakAfter: "",
        breakBefore: "",
        breakInside: "",
        captionSide: "",
        caretColor: "",
        clear: "",
        clip: "",
        clipPath: "",
        clipRule: "",
        color: "",
        colorInterpolation: "",
        colorInterpolationFilters: "",
        colorScheme: "",
        columnCount: "",
        columnFill: "",
        columnGap: "",
        columnRule: "",
        columnRuleColor: "",
        columnRuleStyle: "",
        columnRuleWidth: "",
        columnSpan: "",
        columnWidth: "",
        columns: "",
        contain: "",
        containIntrinsicBlockSize: "",
        containIntrinsicHeight: "",
        containIntrinsicInlineSize: "",
        containIntrinsicSize: "",
        containIntrinsicWidth: "",
        container: "",
        containerName: "",
        containerType: "",
        content: "",
        counterIncrement: "",
        counterReset: "",
        counterSet: "",
        cssFloat: "",
        cssText: "",
        cursor: "",
        direction: "",
        display: "",
        dominantBaseline: "",
        emptyCells: "",
        fill: "",
        fillOpacity: "",
        fillRule: "",
        filter: "",
        flex: "",
        flexBasis: "",
        flexDirection: "",
        flexFlow: "",
        flexGrow: "",
        flexShrink: "",
        flexWrap: "",
        float: "",
        floodColor: "",
        floodOpacity: "",
        font: "",
        fontFamily: "",
        fontFeatureSettings: "",
        fontKerning: "",
        fontOpticalSizing: "",
        fontPalette: "",
        fontSize: "",
        fontSizeAdjust: "",
        fontStretch: "",
        fontStyle: "",
        fontSynthesis: "",
        fontSynthesisSmallCaps: "",
        fontSynthesisStyle: "",
        fontSynthesisWeight: "",
        fontVariant: "",
        fontVariantAlternates: "",
        fontVariantCaps: "",
        fontVariantEastAsian: "",
        fontVariantLigatures: "",
        fontVariantNumeric: "",
        fontVariantPosition: "",
        fontVariationSettings: "",
        fontWeight: "",
        forcedColorAdjust: "",
        gap: "",
        grid: "",
        gridArea: "",
        gridAutoColumns: "",
        gridAutoFlow: "",
        gridAutoRows: "",
        gridColumn: "",
        gridColumnEnd: "",
        gridColumnGap: "",
        gridColumnStart: "",
        gridGap: "",
        gridRow: "",
        gridRowEnd: "",
        gridRowGap: "",
        gridRowStart: "",
        gridTemplate: "",
        gridTemplateAreas: "",
        gridTemplateColumns: "",
        gridTemplateRows: "",
        hyphenateCharacter: "",
        hyphens: "",
        imageOrientation: "",
        imageRendering: "",
        inlineSize: "",
        inset: "",
        insetBlock: "",
        insetBlockEnd: "",
        insetBlockStart: "",
        insetInline: "",
        insetInlineEnd: "",
        insetInlineStart: "",
        isolation: "",
        justifyContent: "",
        justifyItems: "",
        justifySelf: "",
        left: "",
        length: 0,
        letterSpacing: "",
        lightingColor: "",
        lineBreak: "",
        lineHeight: "",
        listStyle: "",
        listStyleImage: "",
        listStylePosition: "",
        listStyleType: "",
        margin: "",
        marginBlock: "",
        marginBlockEnd: "",
        marginBlockStart: "",
        marginBottom: "",
        marginInline: "",
        marginInlineEnd: "",
        marginInlineStart: "",
        marginLeft: "",
        marginRight: "",
        marginTop: "",
        marker: "",
        markerEnd: "",
        markerMid: "",
        markerStart: "",
        mask: "",
        maskClip: "",
        maskComposite: "",
        maskImage: "",
        maskMode: "",
        maskOrigin: "",
        maskPosition: "",
        maskRepeat: "",
        maskSize: "",
        maskType: "",
        mathStyle: "",
        maxBlockSize: "",
        maxHeight: "",
        maxInlineSize: "",
        maxWidth: "",
        minBlockSize: "",
        minHeight: "",
        minInlineSize: "",
        minWidth: "",
        mixBlendMode: "",
        objectFit: "",
        objectPosition: "",
        offset: "",
        offsetDistance: "",
        offsetPath: "",
        offsetRotate: "",
        opacity: "",
        order: "",
        orphans: "",
        outline: "",
        outlineColor: "",
        outlineOffset: "",
        outlineStyle: "",
        outlineWidth: "",
        overflow: "",
        overflowAnchor: "",
        overflowClipMargin: "",
        overflowWrap: "",
        overflowX: "",
        overflowY: "",
        overscrollBehavior: "",
        overscrollBehaviorBlock: "",
        overscrollBehaviorInline: "",
        overscrollBehaviorX: "",
        overscrollBehaviorY: "",
        padding: "",
        paddingBlock: "",
        paddingBlockEnd: "",
        paddingBlockStart: "",
        paddingBottom: "",
        paddingInline: "",
        paddingInlineEnd: "",
        paddingInlineStart: "",
        paddingLeft: "",
        paddingRight: "",
        paddingTop: "",
        page: "",
        pageBreakAfter: "",
        pageBreakBefore: "",
        pageBreakInside: "",
        paintOrder: "",
        parentRule: null,
        perspective: "",
        perspectiveOrigin: "",
        placeContent: "",
        placeItems: "",
        placeSelf: "",
        pointerEvents: "",
        position: "",
        printColorAdjust: "",
        quotes: "",
        resize: "",
        right: "",
        rotate: "",
        rowGap: "",
        rubyPosition: "",
        scale: "",
        scrollBehavior: "",
        scrollMargin: "",
        scrollMarginBlock: "",
        scrollMarginBlockEnd: "",
        scrollMarginBlockStart: "",
        scrollMarginBottom: "",
        scrollMarginInline: "",
        scrollMarginInlineEnd: "",
        scrollMarginInlineStart: "",
        scrollMarginLeft: "",
        scrollMarginRight: "",
        scrollMarginTop: "",
        scrollPadding: "",
        scrollPaddingBlock: "",
        scrollPaddingBlockEnd: "",
        scrollPaddingBlockStart: "",
        scrollPaddingBottom: "",
        scrollPaddingInline: "",
        scrollPaddingInlineEnd: "",
        scrollPaddingInlineStart: "",
        scrollPaddingLeft: "",
        scrollPaddingRight: "",
        scrollPaddingTop: "",
        scrollSnapAlign: "",
        scrollSnapStop: "",
        scrollSnapType: "",
        scrollbarGutter: "",
        shapeImageThreshold: "",
        shapeMargin: "",
        shapeOutside: "",
        shapeRendering: "",
        stopColor: "",
        stopOpacity: "",
        stroke: "",
        strokeDasharray: "",
        strokeDashoffset: "",
        strokeLinecap: "",
        strokeLinejoin: "",
        strokeMiterlimit: "",
        strokeOpacity: "",
        strokeWidth: "",
        tabSize: "",
        tableLayout: "",
        textAlign: "",
        textAlignLast: "",
        textAnchor: "",
        textCombineUpright: "",
        textDecoration: "",
        textDecorationColor: "",
        textDecorationLine: "",
        textDecorationSkipInk: "",
        textDecorationStyle: "",
        textDecorationThickness: "",
        textEmphasis: "",
        textEmphasisColor: "",
        textEmphasisPosition: "",
        textEmphasisStyle: "",
        textIndent: "",
        textOrientation: "",
        textOverflow: "",
        textRendering: "",
        textShadow: "",
        textTransform: "",
        textUnderlineOffset: "",
        textUnderlinePosition: "",
        top: "",
        touchAction: "",
        transform: "",
        transformBox: "",
        transformOrigin: "",
        transformStyle: "",
        transition: "",
        transitionDelay: "",
        transitionDuration: "",
        transitionProperty: "",
        transitionTimingFunction: "",
        translate: "",
        unicodeBidi: "",
        userSelect: "",
        verticalAlign: "",
        visibility: "",
        webkitAlignContent: "",
        webkitAlignItems: "",
        webkitAlignSelf: "",
        webkitAnimation: "",
        webkitAnimationDelay: "",
        webkitAnimationDirection: "",
        webkitAnimationDuration: "",
        webkitAnimationFillMode: "",
        webkitAnimationIterationCount: "",
        webkitAnimationName: "",
        webkitAnimationPlayState: "",
        webkitAnimationTimingFunction: "",
        webkitAppearance: "",
        webkitBackfaceVisibility: "",
        webkitBackgroundClip: "",
        webkitBackgroundOrigin: "",
        webkitBackgroundSize: "",
        webkitBorderBottomLeftRadius: "",
        webkitBorderBottomRightRadius: "",
        webkitBorderRadius: "",
        webkitBorderTopLeftRadius: "",
        webkitBorderTopRightRadius: "",
        webkitBoxAlign: "",
        webkitBoxFlex: "",
        webkitBoxOrdinalGroup: "",
        webkitBoxOrient: "",
        webkitBoxPack: "",
        webkitBoxShadow: "",
        webkitBoxSizing: "",
        webkitFilter: "",
        webkitFlex: "",
        webkitFlexBasis: "",
        webkitFlexDirection: "",
        webkitFlexFlow: "",
        webkitFlexGrow: "",
        webkitFlexShrink: "",
        webkitFlexWrap: "",
        webkitJustifyContent: "",
        webkitLineClamp: "",
        webkitMask: "",
        webkitMaskBoxImage: "",
        webkitMaskBoxImageOutset: "",
        webkitMaskBoxImageRepeat: "",
        webkitMaskBoxImageSlice: "",
        webkitMaskBoxImageSource: "",
        webkitMaskBoxImageWidth: "",
        webkitMaskClip: "",
        webkitMaskComposite: "",
        webkitMaskImage: "",
        webkitMaskOrigin: "",
        webkitMaskPosition: "",
        webkitMaskRepeat: "",
        webkitMaskSize: "",
        webkitOrder: "",
        webkitPerspective: "",
        webkitPerspectiveOrigin: "",
        webkitTextFillColor: "",
        webkitTextSizeAdjust: "",
        webkitTextStroke: "",
        webkitTextStrokeColor: "",
        webkitTextStrokeWidth: "",
        webkitTransform: "",
        webkitTransformOrigin: "",
        webkitTransformStyle: "",
        webkitTransition: "",
        webkitTransitionDelay: "",
        webkitTransitionDuration: "",
        webkitTransitionProperty: "",
        webkitTransitionTimingFunction: "",
        webkitUserSelect: "",
        whiteSpace: "",
        widows: "",
        willChange: "",
        wordBreak: "",
        wordSpacing: "",
        wordWrap: "",
        writingMode: "",
        zIndex: "",
        getPropertyPriority: function (property: string): string {
            throw new Error("Function not implemented.")
        },
        getPropertyValue: function (property: string): string {
            throw new Error("Function not implemented.")
        },
        item: function (index: number): string {
            throw new Error("Function not implemented.")
        },
        removeProperty: function (property: string): string {
            throw new Error("Function not implemented.")
        },
        setProperty: function (property: string, value: string | null, priority?: string | undefined): void {
            throw new Error("Function not implemented.")
        },
        [Symbol.iterator]: function (): IterableIterator<string> {
            throw new Error("Function not implemented.")
        }
    };

    const clonedElement = React.cloneElement(props.children as ReactElement<BorderProps|HTMLElement>,{
        style:{...styleObj, color:'red'}
    }, 'Goodbye, world!');
     console.log(clonedElement);
    const renderContent = React.cloneElement(React.Children.only(props.children) as React.ReactElement<WindowProps>, {
       
    })
    // const renderContent = React.cloneElement(props.children, {
    //     style: {

    //     }
    //   })
    return (
        <div style={style}>
            {
                clonedElement
                //React.Children.only(props.children)
            }
        </div>
    )
}
//Window.defaultProps = defaultProps;
export default Window